# Utilise l'image SDK pour permettre la compilation et 'dotnet watch'
FROM mcr.microsoft.com/dotnet/sdk:9.0
LABEL stage=dev-env
WORKDIR /app
RUN echo '#!/bin/sh\nfind /app -type d \\( -name "bin" -o -name "obj" \\) -exec rm -rf {} + 2>/dev/null || true' > /clean.sh && chmod +x /clean.sh
# La commande 'dotnet watch' lancée par docker-compose se chargera du reste.
# Le code sera monté via le volume.